export type BgImageIds =
  | "hover-player-1"
  | "hover-player-2"
  | "bg"
  | "bg-player-1"
  | "bg-player-2"
  | "center-1-1"
  | "center-1-2"
  | "center-2-1"
  | "center-2-2"
  | "player-1-start"
  | "player-1-end"
  | "player-1-3"
  | "player-1-4"
  | "player-2-start"
  | "player-2-end"
  | "player-2-3"
  | "player-2-4"
